services:
  _defaults:
      autowire: true
      autoconfigure: true
      public: false
      bind:
          $extension: '@Zikula\EZCommentsModule\ZikulaEZCommentsModule'

  Zikula\EZCommentsModule\:
      resource: '../../*'
      exclude: '../../{bootstrap.php,Tests,vendor}'
